### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by iSentrie** [CarlosVergikosk/fivem-chopshop#2]
X

**Comment by CarlosVergikosk** [comment]
it works for me, since you dont have any specific error, maybe you are not doing things right ;)

**Comment by vichuvrn** [comment]
@XvenDeR sorry to mention here..i want to contact you to talk about esx fishing you forked from me..can you give me your discord id.

**Comment by XvenDeR** [comment]
> @XvenDeR sorry to mention here..i want to contact you to talk about esx fishing you forked from me..can you give me your discord id.

i never used it so i can't tell anything about it.

**Comment by vichuvrn** [comment]
@XvenDeR Not about its working .. some other thing.. i will text if you give the discord id

**Comment by vichuvrn** [comment]
@XvenDeR  if you are not using the repo.. can you please delete the repo and store it locally rather than on github.

**Comment by XvenDeR** [comment]
> @XvenDeR if you are not using the repo.. can you please delete the repo and store it locally rather than on github.

Is that what you wanted to tell? If so, yes I can.

**Comment by vichuvrn** [comment]
@XvenDeR yes. Please delete it and please remove my discord id from read me.. store it locally if you want...i have a reason for it..if you give discord id i will tell otherwise leave it.

**Comment by XvenDeR** [comment]
> @XvenDeR yes. Please delete it and please remove my discord id from read me.. store it locally if you want...i have a reason for it..if you give discord id i will tell otherwise leave it.

I will donit as soon as I get to PC, sorry.

**Comment by vichuvrn** [comment]
@XvenDeR  no need to say sorry.. i should tell thanks to you for responding.. You don't have Discord???

**Comment by XvenDeR** [comment]
> @XvenDeR no need to say sorry.. i should tell thanks to you for responding.. You don't have Discord???

I do, u still need it?

**Comment by vichuvrn** [comment]
@XvenDeR  if you dont mind , because its awkward talking here

**Comment by XvenDeR** [comment]
> @XvenDeR if you dont mind , because its awkward talking here . i have one more thing to add

iSentrie#9617

**Comment by vichuvrn** [comment]
@CarlosVergikosk can you please delete this issue. We talked a lot here :)
